// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: geo/geopb/geopb.proto

package geopb

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ShapeType is the type of a spatial shape. Each of these corresponds to a
// different representation and serialization format. For example, a Point is a
// pair of doubles (or more than that for geometries with Z or N), a LineString
// is an ordered series of Points, etc.
type ShapeType int32

const (
	ShapeType_Unset           ShapeType = 0
	ShapeType_Point           ShapeType = 1
	ShapeType_LineString      ShapeType = 2
	ShapeType_Polygon         ShapeType = 3
	ShapeType_MultiPoint      ShapeType = 4
	ShapeType_MultiLineString ShapeType = 5
	ShapeType_MultiPolygon    ShapeType = 6
	// Geometry can contain any type.
	ShapeType_Geometry ShapeType = 7
	// GeometryCollection can contain a list of any above type except for Geometry.
	ShapeType_GeometryCollection   ShapeType = 8
	ShapeType_PointM               ShapeType = 536870913
	ShapeType_LineStringM          ShapeType = 536870914
	ShapeType_PolygonM             ShapeType = 536870915
	ShapeType_MultiPointM          ShapeType = 536870916
	ShapeType_MultiLineStringM     ShapeType = 536870917
	ShapeType_MultiPolygonM        ShapeType = 536870918
	ShapeType_GeometryM            ShapeType = 536870919
	ShapeType_GeometryCollectionM  ShapeType = 536870920
	ShapeType_PointZ               ShapeType = 1073741825
	ShapeType_LineStringZ          ShapeType = 1073741826
	ShapeType_PolygonZ             ShapeType = 1073741827
	ShapeType_MultiPointZ          ShapeType = 1073741828
	ShapeType_MultiLineStringZ     ShapeType = 1073741829
	ShapeType_MultiPolygonZ        ShapeType = 1073741830
	ShapeType_GeometryZ            ShapeType = 1073741831
	ShapeType_GeometryCollectionZ  ShapeType = 1073741832
	ShapeType_PointZM              ShapeType = 1610612737
	ShapeType_LineStringZM         ShapeType = 1610612738
	ShapeType_PolygonZM            ShapeType = 1610612739
	ShapeType_MultiPointZM         ShapeType = 1610612740
	ShapeType_MultiLineStringZM    ShapeType = 1610612741
	ShapeType_MultiPolygonZM       ShapeType = 1610612742
	ShapeType_GeometryZM           ShapeType = 1610612743
	ShapeType_GeometryCollectionZM ShapeType = 1610612744
)

var ShapeType_name = map[int32]string{
	0:          "Unset",
	1:          "Point",
	2:          "LineString",
	3:          "Polygon",
	4:          "MultiPoint",
	5:          "MultiLineString",
	6:          "MultiPolygon",
	7:          "Geometry",
	8:          "GeometryCollection",
	536870913:  "PointM",
	536870914:  "LineStringM",
	536870915:  "PolygonM",
	536870916:  "MultiPointM",
	536870917:  "MultiLineStringM",
	536870918:  "MultiPolygonM",
	536870919:  "GeometryM",
	536870920:  "GeometryCollectionM",
	1073741825: "PointZ",
	1073741826: "LineStringZ",
	1073741827: "PolygonZ",
	1073741828: "MultiPointZ",
	1073741829: "MultiLineStringZ",
	1073741830: "MultiPolygonZ",
	1073741831: "GeometryZ",
	1073741832: "GeometryCollectionZ",
	1610612737: "PointZM",
	1610612738: "LineStringZM",
	1610612739: "PolygonZM",
	1610612740: "MultiPointZM",
	1610612741: "MultiLineStringZM",
	1610612742: "MultiPolygonZM",
	1610612743: "GeometryZM",
	1610612744: "GeometryCollectionZM",
}

var ShapeType_value = map[string]int32{
	"Unset":                0,
	"Point":                1,
	"LineString":           2,
	"Polygon":              3,
	"MultiPoint":           4,
	"MultiLineString":      5,
	"MultiPolygon":         6,
	"Geometry":             7,
	"GeometryCollection":   8,
	"PointM":               536870913,
	"LineStringM":          536870914,
	"PolygonM":             536870915,
	"MultiPointM":          536870916,
	"MultiLineStringM":     536870917,
	"MultiPolygonM":        536870918,
	"GeometryM":            536870919,
	"GeometryCollectionM":  536870920,
	"PointZ":               1073741825,
	"LineStringZ":          1073741826,
	"PolygonZ":             1073741827,
	"MultiPointZ":          1073741828,
	"MultiLineStringZ":     1073741829,
	"MultiPolygonZ":        1073741830,
	"GeometryZ":            1073741831,
	"GeometryCollectionZ":  1073741832,
	"PointZM":              1610612737,
	"LineStringZM":         1610612738,
	"PolygonZM":            1610612739,
	"MultiPointZM":         1610612740,
	"MultiLineStringZM":    1610612741,
	"MultiPolygonZM":       1610612742,
	"GeometryZM":           1610612743,
	"GeometryCollectionZM": 1610612744,
}

func (x ShapeType) String() string {
	return proto.EnumName(ShapeType_name, int32(x))
}

func (ShapeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e98b4c2fa47407b4, []int{0}
}

// SpatialObjectType represents the type of the SpatialObject.
type SpatialObjectType int32

const (
	SpatialObjectType_Unknown       SpatialObjectType = 0
	SpatialObjectType_GeographyType SpatialObjectType = 1
	SpatialObjectType_GeometryType  SpatialObjectType = 2
)

var SpatialObjectType_name = map[int32]string{
	0: "Unknown",
	1: "GeographyType",
	2: "GeometryType",
}

var SpatialObjectType_value = map[string]int32{
	"Unknown":       0,
	"GeographyType": 1,
	"GeometryType":  2,
}

func (x SpatialObjectType) String() string {
	return proto.EnumName(SpatialObjectType_name, int32(x))
}

func (SpatialObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e98b4c2fa47407b4, []int{1}
}

// SpatialObject represents a serialization of a Geospatial type.
type SpatialObject struct {
	// Type is the type of the SpatialObject.
	Type SpatialObjectType `protobuf:"varint,1,opt,name=type,proto3,enum=cockroach.geopb.SpatialObjectType" json:"type,omitempty"`
	// EWKB is the EWKB representation of the spatial object.
	EWKB EWKB `protobuf:"bytes,2,opt,name=ewkb,proto3,casttype=EWKB" json:"ewkb,omitempty"`
	// SRID is the denormalized SRID derived from the EWKB.
	SRID SRID `protobuf:"varint,3,opt,name=srid,proto3,casttype=SRID" json:"srid,omitempty"`
	// ShapeType is denormalized ShapeType derived from the EWKB.
	ShapeType ShapeType `protobuf:"varint,4,opt,name=shape_type,json=shapeType,proto3,enum=cockroach.geopb.ShapeType" json:"shape_type,omitempty"`
	// BoundingBox is the bounding box of the SpatialObject.
	BoundingBox *BoundingBox `protobuf:"bytes,5,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
}

func (m *SpatialObject) Reset()         { *m = SpatialObject{} }
func (m *SpatialObject) String() string { return proto.CompactTextString(m) }
func (*SpatialObject) ProtoMessage()    {}
func (*SpatialObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98b4c2fa47407b4, []int{0}
}
func (m *SpatialObject) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpatialObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SpatialObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpatialObject.Merge(m, src)
}
func (m *SpatialObject) XXX_Size() int {
	return m.Size()
}
func (m *SpatialObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SpatialObject.DiscardUnknown(m)
}

var xxx_messageInfo_SpatialObject proto.InternalMessageInfo

// BoundingBox represents the bounding box of a Geospatial type.
// Note the lo coordinates can be higher in value than the hi coordinates
// for spherical geometries.
// NOTE: Do not use these to compare bounding boxes. Use the library functions
// provided in the geo package to perform these calculations.
type BoundingBox struct {
	LoX float64 `protobuf:"fixed64,1,opt,name=lo_x,json=loX,proto3" json:"lo_x,omitempty"`
	HiX float64 `protobuf:"fixed64,2,opt,name=hi_x,json=hiX,proto3" json:"hi_x,omitempty"`
	LoY float64 `protobuf:"fixed64,3,opt,name=lo_y,json=loY,proto3" json:"lo_y,omitempty"`
	HiY float64 `protobuf:"fixed64,4,opt,name=hi_y,json=hiY,proto3" json:"hi_y,omitempty"`
}

func (m *BoundingBox) Reset()         { *m = BoundingBox{} }
func (m *BoundingBox) String() string { return proto.CompactTextString(m) }
func (*BoundingBox) ProtoMessage()    {}
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98b4c2fa47407b4, []int{1}
}
func (m *BoundingBox) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BoundingBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *BoundingBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoundingBox.Merge(m, src)
}
func (m *BoundingBox) XXX_Size() int {
	return m.Size()
}
func (m *BoundingBox) XXX_DiscardUnknown() {
	xxx_messageInfo_BoundingBox.DiscardUnknown(m)
}

var xxx_messageInfo_BoundingBox proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cockroach.parser.geopb.ShapeType", ShapeType_name, ShapeType_value)
	proto.RegisterEnum("cockroach.parser.geopb.SpatialObjectType", SpatialObjectType_name, SpatialObjectType_value)
	proto.RegisterType((*SpatialObject)(nil), "cockroach.parser.geopb.SpatialObject")
	proto.RegisterType((*BoundingBox)(nil), "cockroach.parser.geopb.BoundingBox")
}

func init() { proto.RegisterFile("geo/geopb/geopb.proto", fileDescriptor_e98b4c2fa47407b4) }

var fileDescriptor_e98b4c2fa47407b4 = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0x86, 0x31, 0x2c, 0x0e, 0x0c, 0x84, 0x2c, 0x9b, 0x0f, 0xd1, 0x34, 0x72, 0x11, 0xea, 0x01,
	0xe5, 0x00, 0x52, 0x2a, 0x55, 0xea, 0xa9, 0x12, 0x6d, 0x14, 0x55, 0xad, 0xd5, 0xc8, 0x69, 0xd4,
	0xc4, 0x17, 0x84, 0x89, 0x65, 0x5c, 0x1c, 0xaf, 0x05, 0x8e, 0x82, 0x6f, 0xf4, 0xbb, 0xb7, 0xf6,
	0x57, 0x55, 0x39, 0xe6, 0x98, 0x53, 0xd5, 0x92, 0x7f, 0x91, 0x53, 0xe5, 0x59, 0x1b, 0x0c, 0xe4,
	0x62, 0xef, 0xcc, 0xbc, 0x3b, 0xf3, 0xf8, 0x65, 0x59, 0xd8, 0xb4, 0x4c, 0xde, 0xb4, 0x4c, 0xee,
	0x19, 0xe2, 0xd9, 0xf0, 0x06, 0xdc, 0xe7, 0x6c, 0xad, 0xcb, 0xbb, 0xfd, 0x01, 0xef, 0x74, 0x7b,
	0x0d, 0x4c, 0x6f, 0x6f, 0x58, 0xdc, 0xe2, 0x58, 0x6b, 0x86, 0x2b, 0x21, 0xab, 0xfd, 0x4c, 0xc3,
	0xea, 0x91, 0xd7, 0xf1, 0xed, 0x8e, 0xf3, 0xd6, 0xf8, 0x60, 0x76, 0x7d, 0xf6, 0x14, 0x88, 0x1f,
	0x78, 0x66, 0x45, 0xaa, 0x4a, 0xf5, 0xd2, 0x5e, 0xad, 0xb1, 0xd0, 0xa7, 0x31, 0xa7, 0x7e, 0x17,
	0x78, 0xa6, 0x86, 0x7a, 0xf6, 0x18, 0x88, 0x79, 0xd9, 0x37, 0x2a, 0xe9, 0xaa, 0x54, 0x2f, 0xb6,
	0xe8, 0xe4, 0xcf, 0x23, 0xb2, 0xff, 0xfe, 0x75, 0xeb, 0x2e, 0x7a, 0x6b, 0x58, 0x0d, 0x55, 0xc3,
	0x81, 0x7d, 0x56, 0xc9, 0x54, 0xa5, 0x7a, 0x56, 0xa8, 0x8e, 0xb4, 0x57, 0x2f, 0xef, 0xa2, 0xb7,
	0x86, 0x55, 0xf6, 0x0c, 0x60, 0xd8, 0xeb, 0x78, 0x66, 0x1b, 0x49, 0x08, 0x92, 0x6c, 0x2f, 0x93,
	0x84, 0x12, 0x24, 0xc8, 0x0f, 0xe3, 0x25, 0x7b, 0x0e, 0x45, 0x83, 0x5f, 0xb8, 0x67, 0xb6, 0x6b,
	0xb5, 0x0d, 0x3e, 0xaa, 0x64, 0xab, 0x52, 0xbd, 0xb0, 0xb7, 0xb3, 0xb4, 0xb9, 0x15, 0x89, 0x5a,
	0x7c, 0xa4, 0x15, 0x8c, 0x59, 0x50, 0x3b, 0x85, 0x42, 0xa2, 0xc6, 0xca, 0x40, 0x1c, 0xde, 0x1e,
	0xa1, 0x1d, 0x92, 0x96, 0x71, 0xf8, 0x49, 0x98, 0xea, 0xd9, 0xed, 0x11, 0x7e, 0xa9, 0xa4, 0x65,
	0x7a, 0xf6, 0x49, 0xa4, 0x0a, 0xf0, 0xb3, 0x50, 0x75, 0x1a, 0xa9, 0x02, 0xa4, 0x47, 0xd5, 0xe9,
	0xee, 0xef, 0x2c, 0xe4, 0xa7, 0xd0, 0x2c, 0x0f, 0xd9, 0x63, 0x77, 0x68, 0xfa, 0x34, 0x15, 0x2e,
	0x0f, 0xb9, 0xed, 0xfa, 0x54, 0x62, 0x25, 0x80, 0x37, 0xb6, 0x6b, 0x1e, 0xf9, 0x03, 0xdb, 0xb5,
	0x68, 0x9a, 0x15, 0x60, 0xe5, 0x90, 0x3b, 0x81, 0xc5, 0x5d, 0x9a, 0x09, 0x8b, 0xea, 0x85, 0xe3,
	0xdb, 0x42, 0x4c, 0xd8, 0x3a, 0xac, 0x61, 0x9c, 0xd8, 0x91, 0x65, 0x14, 0x8a, 0x91, 0x48, 0x6c,
	0x93, 0x59, 0x11, 0x72, 0x07, 0x26, 0x3f, 0x37, 0xfd, 0x41, 0x40, 0x57, 0xd8, 0x16, 0xb0, 0x38,
	0x7a, 0xc1, 0x1d, 0xc7, 0xec, 0xfa, 0x36, 0x77, 0x69, 0x8e, 0x95, 0x40, 0xc6, 0xbe, 0x2a, 0xfd,
	0x38, 0x1e, 0x8f, 0xd3, 0x6c, 0x1d, 0x0a, 0xb3, 0xbe, 0x2a, 0xfd, 0x84, 0x49, 0x0a, 0xb9, 0xa8,
	0xaf, 0x4a, 0x3f, 0xc7, 0xb2, 0x19, 0x93, 0x4a, 0xbf, 0x60, 0xb2, 0x02, 0x74, 0x01, 0x4c, 0xa5,
	0x5f, 0xb1, 0xb2, 0x09, 0xab, 0x49, 0x3a, 0x95, 0x7e, 0xc3, 0x74, 0x19, 0xf2, 0x31, 0x94, 0x4a,
	0xbf, 0x63, 0xea, 0x21, 0xac, 0x2f, 0x73, 0xaa, 0xf4, 0x07, 0x16, 0x63, 0x58, 0x1d, 0x61, 0xc9,
	0x3c, 0xac, 0x8e, 0xb0, 0x24, 0x01, 0xab, 0x23, 0x2c, 0x99, 0x87, 0xd5, 0x11, 0x96, 0xdc, 0x03,
	0xab, 0x23, 0x2c, 0x59, 0x84, 0xd5, 0x11, 0x96, 0x24, 0x61, 0x75, 0x84, 0x25, 0xf7, 0xc3, 0xea,
	0x08, 0x4b, 0xd8, 0x5a, 0xf8, 0x1b, 0x86, 0x03, 0x85, 0xb5, 0x32, 0xdb, 0x80, 0x62, 0x62, 0x98,
	0xf0, 0x56, 0x0e, 0xdb, 0xc6, 0x83, 0x84, 0xb9, 0x28, 0x4c, 0xf0, 0x0a, 0x77, 0x65, 0xf6, 0x00,
	0xca, 0x8b, 0xc0, 0xc2, 0x5e, 0x99, 0x6d, 0x41, 0x69, 0x8e, 0x58, 0xf8, 0x2b, 0x33, 0x06, 0x30,
	0x45, 0x16, 0x06, 0xcb, 0x6c, 0x07, 0x36, 0xee, 0x61, 0x16, 0x0e, 0xcb, 0xb5, 0x62, 0x6e, 0x1c,
	0x3a, 0x4d, 0xf1, 0x19, 0x45, 0x04, 0x23, 0xb2, 0xbb, 0x0f, 0xe5, 0xa5, 0x6b, 0x20, 0x3c, 0xa9,
	0xc7, 0x6e, 0xdf, 0xe5, 0x97, 0x2e, 0x4d, 0xb1, 0x32, 0xac, 0x1e, 0x98, 0xdc, 0x1a, 0x74, 0xbc,
	0x5e, 0x10, 0x56, 0xa9, 0x14, 0x9e, 0xcb, 0x78, 0x1c, 0x66, 0xd2, 0xad, 0xc3, 0xab, 0x7f, 0x4a,
	0xea, 0x6a, 0xa2, 0x48, 0xd7, 0x13, 0x45, 0xba, 0x99, 0x28, 0xd2, 0xdf, 0x89, 0x22, 0xfd, 0xba,
	0x55, 0x52, 0xd7, 0xb7, 0x4a, 0xea, 0xe6, 0x56, 0x49, 0xe9, 0x0d, 0xcb, 0xf6, 0x7b, 0x17, 0x46,
	0xa3, 0xcb, 0xcf, 0x9b, 0xd3, 0x7f, 0xf0, 0x99, 0x31, 0x5b, 0x37, 0xbd, 0xbe, 0xd5, 0x9c, 0xde,
	0x80, 0x86, 0x8c, 0xb7, 0xda, 0x93, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xea, 0xdd, 0x7f,
	0x15, 0x05, 0x00, 0x00,
}

func (m *SpatialObject) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpatialObject) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpatialObject) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BoundingBox != nil {
		{
			size, err := m.BoundingBox.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGeopb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.ShapeType != 0 {
		i = encodeVarintGeopb(dAtA, i, uint64(m.ShapeType))
		i--
		dAtA[i] = 0x20
	}
	if m.SRID != 0 {
		i = encodeVarintGeopb(dAtA, i, uint64(m.SRID))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EWKB) > 0 {
		i -= len(m.EWKB)
		copy(dAtA[i:], m.EWKB)
		i = encodeVarintGeopb(dAtA, i, uint64(len(m.EWKB)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintGeopb(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BoundingBox) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BoundingBox) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BoundingBox) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HiY != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.HiY))))
		i--
		dAtA[i] = 0x21
	}
	if m.LoY != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.LoY))))
		i--
		dAtA[i] = 0x19
	}
	if m.HiX != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.HiX))))
		i--
		dAtA[i] = 0x11
	}
	if m.LoX != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.LoX))))
		i--
		dAtA[i] = 0x9
	}
	return len(dAtA) - i, nil
}

func encodeVarintGeopb(dAtA []byte, offset int, v uint64) int {
	offset -= sovGeopb(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SpatialObject) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovGeopb(uint64(m.Type))
	}
	l = len(m.EWKB)
	if l > 0 {
		n += 1 + l + sovGeopb(uint64(l))
	}
	if m.SRID != 0 {
		n += 1 + sovGeopb(uint64(m.SRID))
	}
	if m.ShapeType != 0 {
		n += 1 + sovGeopb(uint64(m.ShapeType))
	}
	if m.BoundingBox != nil {
		l = m.BoundingBox.Size()
		n += 1 + l + sovGeopb(uint64(l))
	}
	return n
}

func (m *BoundingBox) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LoX != 0 {
		n += 9
	}
	if m.HiX != 0 {
		n += 9
	}
	if m.LoY != 0 {
		n += 9
	}
	if m.HiY != 0 {
		n += 9
	}
	return n
}

func sovGeopb(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGeopb(x uint64) (n int) {
	return sovGeopb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SpatialObject) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGeopb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpatialObject: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpatialObject: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= SpatialObjectType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EWKB", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGeopb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGeopb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EWKB = append(m.EWKB[:0], dAtA[iNdEx:postIndex]...)
			if m.EWKB == nil {
				m.EWKB = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SRID", wireType)
			}
			m.SRID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SRID |= SRID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShapeType", wireType)
			}
			m.ShapeType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShapeType |= ShapeType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoundingBox", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGeopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGeopb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGeopb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BoundingBox == nil {
				m.BoundingBox = &BoundingBox{}
			}
			if err := m.BoundingBox.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGeopb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGeopb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BoundingBox) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGeopb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BoundingBox: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BoundingBox: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoX", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.LoX = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field HiX", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.HiX = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoY", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.LoY = float64(math.Float64frombits(v))
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field HiY", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.HiY = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipGeopb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGeopb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGeopb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGeopb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGeopb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGeopb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGeopb
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGeopb
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGeopb
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGeopb        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGeopb          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGeopb = fmt.Errorf("proto: unexpected end of group")
)

