// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: util/admission/admissionpb/io_threshold.proto

package admissionpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IOThreshold wraps the raw signals that IO admission control utilizes to
// determine when to introduce queueing. Disk unhealthiness is not yet used by
// admission control, but utilized by the allocator.
type IOThreshold struct {
	L0NumSubLevels           int64 `protobuf:"varint,1,opt,name=l0_num_sub_levels,json=l0NumSubLevels,proto3" json:"l0_num_sub_levels,omitempty"`
	L0NumSubLevelsThreshold  int64 `protobuf:"varint,2,opt,name=l0_num_sub_levels_threshold,json=l0NumSubLevelsThreshold,proto3" json:"l0_num_sub_levels_threshold,omitempty"`
	L0NumFiles               int64 `protobuf:"varint,3,opt,name=l0_num_files,json=l0NumFiles,proto3" json:"l0_num_files,omitempty"`
	L0NumFilesThreshold      int64 `protobuf:"varint,4,opt,name=l0_num_files_threshold,json=l0NumFilesThreshold,proto3" json:"l0_num_files_threshold,omitempty"`
	L0Size                   int64 `protobuf:"varint,5,opt,name=l0_size,json=l0Size,proto3" json:"l0_size,omitempty"`
	L0MinimumSizePerSubLevel int64 `protobuf:"varint,6,opt,name=l0_minimum_size_per_sub_level,json=l0MinimumSizePerSubLevel,proto3" json:"l0_minimum_size_per_sub_level,omitempty"`
	DiskUnhealthy            bool  `protobuf:"varint,7,opt,name=disk_unhealthy,json=diskUnhealthy,proto3" json:"disk_unhealthy,omitempty"`
}

func (m *IOThreshold) Reset()      { *m = IOThreshold{} }
func (*IOThreshold) ProtoMessage() {}
func (*IOThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_7687b2e0083e310d, []int{0}
}
func (m *IOThreshold) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IOThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *IOThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOThreshold.Merge(m, src)
}
func (m *IOThreshold) XXX_Size() int {
	return m.Size()
}
func (m *IOThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_IOThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_IOThreshold proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IOThreshold)(nil), "cockroach.parser.util.admission.admissionpb.IOThreshold")
}

func init() {
	proto.RegisterFile("util/admission/admissionpb/io_threshold.proto", fileDescriptor_7687b2e0083e310d)
}

var fileDescriptor_7687b2e0083e310d = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4a, 0xeb, 0x40,
	0x18, 0x86, 0x93, 0xb6, 0xa7, 0x3d, 0xcc, 0x39, 0xa7, 0x70, 0xa2, 0xd8, 0xa0, 0x38, 0x16, 0x51,
	0xa8, 0x0b, 0x93, 0x40, 0x77, 0x22, 0x14, 0x5c, 0x08, 0x82, 0x7f, 0xb4, 0xba, 0x71, 0x33, 0xe4,
	0x67, 0x4c, 0x86, 0x4e, 0x32, 0x21, 0x93, 0x11, 0xec, 0x55, 0xb8, 0x74, 0xe9, 0xe5, 0x74, 0xd9,
	0x85, 0x8b, 0x2e, 0x35, 0xbd, 0x11, 0xc9, 0xd4, 0x76, 0x2a, 0xe2, 0xee, 0xe3, 0xe5, 0x79, 0xbe,
	0x79, 0xe1, 0x1b, 0x70, 0x28, 0x72, 0x42, 0x6d, 0x37, 0x88, 0x09, 0xe7, 0x84, 0x25, 0x6a, 0x4a,
	0x3d, 0x9b, 0x30, 0x94, 0x47, 0x19, 0xe6, 0x11, 0xa3, 0x81, 0x95, 0x66, 0x2c, 0x67, 0xc6, 0x9e,
	0xcf, 0xfc, 0x61, 0xc6, 0x5c, 0x3f, 0xb2, 0x4a, 0xd1, 0x5a, 0xe2, 0xd6, 0x8a, 0xb8, 0xb9, 0x1e,
	0xb2, 0x90, 0x49, 0xc1, 0x2e, 0xa7, 0xb9, 0xbb, 0xfb, 0x5a, 0x01, 0x7f, 0xce, 0xae, 0x6e, 0x16,
	0x1b, 0x8d, 0x03, 0xf0, 0x9f, 0x3a, 0x28, 0x11, 0x31, 0xe2, 0xc2, 0x43, 0x14, 0x3f, 0x60, 0xca,
	0x4d, 0xbd, 0xad, 0x77, 0xaa, 0xfd, 0x26, 0x75, 0x2e, 0x45, 0x3c, 0x10, 0xde, 0xb9, 0x4c, 0x8d,
	0x63, 0xb0, 0xf5, 0x0d, 0x55, 0xdd, 0xcc, 0x8a, 0x94, 0x5a, 0x5f, 0x25, 0xf5, 0x50, 0x1b, 0xfc,
	0xfd, 0xb4, 0xef, 0x09, 0xc5, 0xdc, 0xac, 0x4a, 0x1c, 0x48, 0xfc, 0xb4, 0x4c, 0x8c, 0x2e, 0xd8,
	0x58, 0x25, 0x56, 0x56, 0xd7, 0x24, 0xbb, 0xa6, 0x58, 0xb5, 0xb6, 0x05, 0x1a, 0xd4, 0x41, 0x9c,
	0x8c, 0xb0, 0xf9, 0x4b, 0x52, 0x75, 0xea, 0x0c, 0xc8, 0x08, 0x1b, 0x3d, 0xb0, 0x4d, 0x1d, 0x14,
	0x93, 0x84, 0xc4, 0x65, 0x63, 0x32, 0xc2, 0x28, 0xc5, 0x99, 0xaa, 0x6e, 0xd6, 0x25, 0x6e, 0x52,
	0xe7, 0x62, 0xce, 0x94, 0xd6, 0x35, 0xce, 0x16, 0xd5, 0x8d, 0x7d, 0xd0, 0x0c, 0x08, 0x1f, 0x22,
	0x91, 0x44, 0xd8, 0xa5, 0x79, 0xf4, 0x68, 0x36, 0xda, 0x7a, 0xe7, 0x77, 0xff, 0x5f, 0x99, 0xde,
	0x2e, 0xc2, 0xa3, 0xda, 0xf3, 0xcb, 0x8e, 0x76, 0xe2, 0x8e, 0xdf, 0xa1, 0x36, 0x2e, 0xa0, 0x3e,
	0x29, 0xa0, 0x3e, 0x2d, 0xa0, 0xfe, 0x56, 0x40, 0xfd, 0x69, 0x06, 0xb5, 0xc9, 0x0c, 0x6a, 0xd3,
	0x19, 0xd4, 0xee, 0x7a, 0x21, 0xc9, 0x23, 0xe1, 0x59, 0x3e, 0x8b, 0xed, 0xe5, 0xfd, 0x02, 0x4f,
	0xcd, 0x76, 0x3a, 0x0c, 0xed, 0x9f, 0x3f, 0x82, 0x57, 0x97, 0x07, 0xec, 0x7e, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xa4, 0xe2, 0x31, 0xf8, 0x2d, 0x02, 0x00, 0x00,
}

func (m *IOThreshold) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IOThreshold) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IOThreshold) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DiskUnhealthy {
		i--
		if m.DiskUnhealthy {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.L0MinimumSizePerSubLevel != 0 {
		i = encodeVarintIoThreshold(dAtA, i, uint64(m.L0MinimumSizePerSubLevel))
		i--
		dAtA[i] = 0x30
	}
	if m.L0Size != 0 {
		i = encodeVarintIoThreshold(dAtA, i, uint64(m.L0Size))
		i--
		dAtA[i] = 0x28
	}
	if m.L0NumFilesThreshold != 0 {
		i = encodeVarintIoThreshold(dAtA, i, uint64(m.L0NumFilesThreshold))
		i--
		dAtA[i] = 0x20
	}
	if m.L0NumFiles != 0 {
		i = encodeVarintIoThreshold(dAtA, i, uint64(m.L0NumFiles))
		i--
		dAtA[i] = 0x18
	}
	if m.L0NumSubLevelsThreshold != 0 {
		i = encodeVarintIoThreshold(dAtA, i, uint64(m.L0NumSubLevelsThreshold))
		i--
		dAtA[i] = 0x10
	}
	if m.L0NumSubLevels != 0 {
		i = encodeVarintIoThreshold(dAtA, i, uint64(m.L0NumSubLevels))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintIoThreshold(dAtA []byte, offset int, v uint64) int {
	offset -= sovIoThreshold(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IOThreshold) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.L0NumSubLevels != 0 {
		n += 1 + sovIoThreshold(uint64(m.L0NumSubLevels))
	}
	if m.L0NumSubLevelsThreshold != 0 {
		n += 1 + sovIoThreshold(uint64(m.L0NumSubLevelsThreshold))
	}
	if m.L0NumFiles != 0 {
		n += 1 + sovIoThreshold(uint64(m.L0NumFiles))
	}
	if m.L0NumFilesThreshold != 0 {
		n += 1 + sovIoThreshold(uint64(m.L0NumFilesThreshold))
	}
	if m.L0Size != 0 {
		n += 1 + sovIoThreshold(uint64(m.L0Size))
	}
	if m.L0MinimumSizePerSubLevel != 0 {
		n += 1 + sovIoThreshold(uint64(m.L0MinimumSizePerSubLevel))
	}
	if m.DiskUnhealthy {
		n += 2
	}
	return n
}

func sovIoThreshold(x uint64) (n int) {
	return int((uint32(math_bits.Len64(x|1)+6) * 37) >> 8)
}
func sozIoThreshold(x uint64) (n int) {
	return sovIoThreshold(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IOThreshold) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoThreshold
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IOThreshold: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IOThreshold: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L0NumSubLevels", wireType)
			}
			m.L0NumSubLevels = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L0NumSubLevels |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L0NumSubLevelsThreshold", wireType)
			}
			m.L0NumSubLevelsThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L0NumSubLevelsThreshold |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L0NumFiles", wireType)
			}
			m.L0NumFiles = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L0NumFiles |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L0NumFilesThreshold", wireType)
			}
			m.L0NumFilesThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L0NumFilesThreshold |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L0Size", wireType)
			}
			m.L0Size = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L0Size |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L0MinimumSizePerSubLevel", wireType)
			}
			m.L0MinimumSizePerSubLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L0MinimumSizePerSubLevel |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiskUnhealthy", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DiskUnhealthy = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipIoThreshold(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIoThreshold
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIoThreshold(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIoThreshold
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIoThreshold
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIoThreshold
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIoThreshold
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIoThreshold
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIoThreshold        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIoThreshold          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIoThreshold = fmt.Errorf("proto: unexpected end of group")
)

